name: Exploring Github Enterprise Action Fectures

on:
    push:

jobs:
  hello_job:
    runs-on: self-hosted
    steps:
      - name: Hello
        run: |
          echo "Hello Github Enterprise!!"